name: Build SVG

on:
  schedule:
    - cron: "0 15 * * *" # 매일 자정 (GMT+9, Best effort scheduling)
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - run: npm install

      - name: Generate readme
        # env:
        #   WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build.js

      - name: Get current KST date
        id: date
        run: echo "date=$(TZ=Asia/Seoul date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Queue-ri
          author_email: qriosity.dev@gmail.com
          message: "ci: Auto build ${{ steps.date.outputs.date }}"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}